refactor log messages

diff --git a/tailscale/rootfs/etc/services.d/tailscaled/post b/tailscale/rootfs/etc/services.d/tailscaled/post
--- a/tailscale/rootfs/etc/services.d/tailscaled/post
+++ b/tailscale/rootfs/etc/services.d/tailscaled/post
@@ -63,37 +63,35 @@ do
 done
 
 # Wait for the network to be available
-while true;
+while ! /opt/tailscale status --json --peers=false --self=false \
+  | jq --exit-status '.BackendState == "Running" or .BackendState == "NeedsLogin"' > /dev/null;
 do
-  if /opt/tailscale status --json --peers=false --self=false \
-    | jq --exit-status '.BackendState == "Running" or .BackendState == "NeedsLogin"' > /dev/null;
-  then
-    IFS=","
-    /opt/tailscale up \
-      --hostname "$(bashio::info.hostname)" \
-      --advertise-exit-node \
-      --accept-routes \
-      --advertise-routes="${routes[*]}" \
-      --advertise-tags="${tags}"
-    break
-  fi
-  # Well... wait a bit more
   sleep 2
 done
+
+# Start Tailscale
+IFS=","
+if ! /opt/tailscale up \
+  --hostname "$(bashio::info.hostname)" \
+  --advertise-exit-node \
+  --accept-routes \
+  --advertise-routes="${routes[*]}" \
+  --advertise-tags="${tags}";
+then
+  bashio::log.error "Unable to start up Tailscale"
+  bashio::exit.nok
+fi
 
 # Wait for the network to be available and logged in
-while true;
+while ! /opt/tailscale status --json --peers=false --self=false \
+  | jq --exit-status '.BackendState == "Running"' > /dev/null
 do
-  if /opt/tailscale status --json --peers=false --self=false \
-    | jq --exit-status '.BackendState == "Running"' > /dev/null;
-  then
-    break
-  fi
-  # Well... wait a bit more
   sleep 2
 done
 
-bashio::log.info "Tailscale is running, configuring Funnel..."
+bashio::log.info "Tailscale is running"
+
+bashio::log.info "Enabling Proxy and Funnel..."
 
 declare ha_service_protocol
 declare domain
@@ -114,17 +112,21 @@ if ! /opt/tailscale status --self=true --peers=false --json \
 then
   bashio::log.warning
   bashio::log.warning "Can't get your Tailscale domain, is HTTPS support enabled?"
-  bashio::log.warning "See the Prerequisites chapter in the add-on's Documentation."
+  bashio::log.warning "See the 'Prerequisites chapter' in the add-on's Documentation."
   bashio::log.warning
   bashio::log.warning ">>> THEN RESTART THIS ADD-ON!!! <<<"
   bashio::log.warning
   bashio::exit.ok
 fi
-
-# Configure Tailscale proxy
 domain=$(/opt/tailscale status --self=true --peers=false --json | jq -rc ".CertDomains[0]")
-/opt/tailscale serve / proxy ${ha_service_protocol}://localhost:$(bashio::core.port)
-bashio::log.info "Your Home Assistant instance is available within your Tailnet VPN at:"
+
+# Set up proxy
+if ! /opt/tailscale serve / proxy ${ha_service_protocol}://localhost:$(bashio::core.port); then
+  bashio::log.error "Unable to configure Tailscale Proxy"
+  bashio::exit.nok
+fi
+bashio::log.info "Tailscale Proxy is enabled:"
+bashio::log.info "  Your Home Assistant instance is available within your Tailnet VPN at"
 bashio::log.info "  https://${domain}"
 
 # Check if funnel is available
@@ -132,15 +134,18 @@ if ! funnel_available=$(/opt/tailscale serve funnel off 2>&1); then
   bashio::log.warning
   bashio::log.warning "${funnel_available}"
   bashio::log.warning "Funnel is not available, is Funnel feature enabled?"
-  bashio::log.warning "See the Required Tailscale configuration chapter in the add-on's Documentation."
+  bashio::log.warning "See the 'Required Tailscale configuration' chapter in the add-on's Documentation."
   bashio::log.warning
   bashio::log.warning ">>> THEN RESTART THIS ADD-ON!!! <<<"
   bashio::log.warning
   bashio::exit.ok
 fi
 
-# Set up Funnel
-if $(/opt/tailscale serve funnel on); then
-  bashio::log.info "Your Homeassistant instance is publicly available on the internet at:"
-  bashio::log.info "  https://${domain}"
+# Set up funnel
+if ! /opt/tailscale serve funnel on; then
+  bashio::log.error "Unable to configure Tailscale Funnel"
+  bashio::exit.nok
 fi
+bashio::log.info "Tailscale Funnel is enabled:"
+bashio::log.info "  Your Homeassistant instance is publicly available on the internet at"
+bashio::log.info "  https://${domain}"
